name: Compile LaTeX to PDF

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX to PDF
        uses: xu-cheng/latex-action@v4
        with:
          root_file: shop-qr-sheet.tex

      - name: Upload PDF and log as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled
          path: |
            shop-qr-sheet.pdf
            shop-qr-sheet.log
